### ISSUE TITLE
Not every case converted

### ISSUE THREAD

**Issue by kostya** [ooxi/entities#7]
in such string only second converted: "`&amp &amp; &AMP;"`, but all cases correct for browser. I actually try to find library which can do this correct and also be fast, right now i using part of myhtml, this method https://github.com/lexborisov/myhtml/blob/master/source/myhtml/myhtml.c#L665, which is fast and html5 standard, but myhtml is a big dependency and also this method hard to use outside of myhtml.

**Comment by ooxi** [comment]
Thanks for the feedback! Could you provide sources for `&amp` and `&AMP;` being valid? I don't think DTDs are case insensitive, otherwise it would not be possible to differentiate between `&Auml;` and `&auml;`

**Comment by kostya** [comment]
i just open this string with browser. and all converted. myhtml also convert all. i dont know all rules btw.

**Comment by ooxi** [comment]
Browsers use many heuristics to also render invalid content. While I see such a functionality being useful, I don't think it's in the scope of this library.

Feel free to fork and adapt however :-)
